### ISSUE TITLE
require_relative error 

### ISSUE THREAD

**Issue by ksharsha72** [SciRuby/iruby#349]
When i did` require_relative config/application`  in my notebook cell , i am getting the following error , could you tell me how to resolve this

```
NoMethodError: undefined method `closed?' for #<IRuby::OStream:0x00005621b1f1c3d0>
Did you mean?  close
/home/sriharsha/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:108:in `tell_err'
/home/sriharsha/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:41:in `error'
/home/sriharsha/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:12:in `rescue in <top (required)>'
/home/sriharsha/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:9:in `<top (required)>'
/home/sriharsha/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/home/sriharsha/.rbenv/versions/2.7.0/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/home/sriharsha/app_autodoc/4.13.0/backend-v5/config/boot.rb:3:in `<top (required)>'
/home/sriharsha/app_autodoc/4.13.0/backend-v5/config/application.rb:1:in `require_relative'
/home/sriharsha/app_autodoc/4.13.0/backend-v5/config/application.rb:1:in `<top (required)>'
(irb):in `require_relative'
(irb):in `<top (required)>'
```

**Comment by simpl1g** [comment]
Same error when trying to load Rails application, worked fine with IRuby 0.4.0

Ruby 3.3.5
Bundler 2.5.18
IRuby 0.8.0

```
Dir.chdir '/home/jovyan/rails_app'
ENV['RAILS_ENV'] = 'development'
require '/home/jovyan/rails_app/config/environment'

NoMethodError: undefined method `closed?' for an instance of IRuby::OStream
/usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/ui/shell.rb:131:in `tell_err'
/usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/ui/shell.rb:46:in `error'
/usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/setup.rb:18:in `rescue in <top (required)>'
/usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.18/lib/bundler/setup.rb:15:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
/home/jovyan/rails_app/config/boot.rb:3:in `<top (required)>'
```

**Comment by sealocal** [comment]
#368 fixes this issue
